# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-08 18:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='pub_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='tag',
            old_name='tag_titlle',
            new_name='tag_title',
        ),
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(default='http://placehold.it/900x300', upload_to='blog/images'),
        ),
    ]
