# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-14 10:47
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20170308_1920'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='text2',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
    ]
