# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-14 10:59
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_article_text2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='text2',
        ),
        migrations.AlterField(
            model_name='article',
            name='text',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
