# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 16:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_article_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='thumbnail',
            field=models.ImageField(blank=True, default='blog/img/thumbnail.jpg', upload_to='media/images'),
        ),
        migrations.AlterField(
            model_name='article',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name='Date de publication'),
        ),
    ]
