# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 16:46
from __future__ import unicode_literals

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20170322_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, upload_to='media/images'),
        ),
    ]
