# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-23 15:09
from __future__ import unicode_literals

from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20170322_1646'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='tag_title',
            new_name='name',
        ),
        migrations.AddField(
            model_name='article',
            name='slug',
            field=models.SlugField(default='popo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tag',
            name='slug',
            field=models.SlugField(default='dd'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='thumbnail',
            field=imagekit.models.fields.ProcessedImageField(blank=True, default='blog/img/thumbnail.jpg', upload_to='media/images'),
        ),
    ]
